### ISSUE TITLE
File/API structure planning steps by default

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#86] opened 2023-05-05 11:25 UTC
It is crucial to have a planning step for changes in file structure, and it should have mandatory approval by users by default.
Before we even begin to make changes to files that are bigger than half the context (32k tokens / 2) we should be able to plan changes in each file's public API with mandatory approval by user by default.

Today, with so much limitation, it is almost impossible to make it autonomous.
Every change or plan can be perfected by GPT-4 many times giving it prompt (Can you do better? Can you improve your plan? And so on).
On the other hand, user should be in control of spending via GPT-4 API, and it should be configurable all guided to have that many second thoughts.

Anyway, it will be completely impossible without https://github.com/irgolic/AutoPR/issues/31 and https://github.com/irgolic/AutoPR/issues/85

Related to https://github.com/irgolic/AutoPR/issues/94

**Comment by irgolic** [comment] 2023-06-08 10:33
It already plans changes while it looks at files, so this is a duplicate of #87.

What would you think of having two separate triggers, one to iterate the plan in the issue, and one to trigger code generation?

**Closed** 2023-11-05 15:19 UTC
